[Bugfix] Fix wrong imports in examples (#1241)
The current script gives

```
Traceback (most recent call last):
  File "/Users/xmxd289/code/openai-agents-python/examples/reasoning_content/main.py", line 19, in <module>
    from agents.types import ResponseOutputRefusal, ResponseOutputText  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'agents.types'
```

because it should be

`from openai.types.responses import ResponseOutputRefusal,
ResponseOutputText`

rather than

`from agents.types import ResponseOutputRefusal, ResponseOutputText`

---------

Co-authored-by: Michelangelo D'Agostino <mda@grainger.com>